name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Localization
  intl: ^0.17.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1

  provider: ^6.0.3

  # Utils 
  uuid: ^3.0.6
  platform_device_id: ^1.0.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.7
  shake: ^2.1.0
  uni_links: ^0.5.1

  # Logs
  logger: ^1.1.0

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  
  # Network
  dio: ^4.0.6

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Autogen
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

  # Firebase
  firebase_core: ^1.20.0
  firebase_remote_config: ^2.0.13
  firebase_crashlytics: ^2.8.6
  firebase_analytics: ^9.3.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  
  # For Testing
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter_native_splash:
  color: "#34C759"
  image: assets/splash/logo.png
  branding: assets/splash/text.png
  branding_mode: bottom
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/env/.env.development
    - assets/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
