name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1

  provider: ^6.0.3

  # Utils 
  uuid: ^3.0.6
  platform_device_id: ^1.0.1
  flutter_dotenv: ^5.0.2

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Autogen
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/env/.env.development
    - assets/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
